server:
  port: 9090
spring:
  servlet:
    multipart:
      # 最大文件大小
      max-file-size: 10MB
      # 最大请求大小
      max-request-size: 10MB
  # json序列化date类型时候防止出现 T
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  redis:
    host: 47.105.46.197
    port: 6379
    password: 123456
    jedis:
      pool:
        max-active: 20 #最大连接数
        max-wait: -1    #最大阻塞等待时间(负数表示没限制)
        max-idle: 5    #最大空闲
        min-idle: 0     #最小空闲
  datasource:
    username: exam_system
    password: root
    url: jdbc:mysql://47.105.46.197:3306/exam_system?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&serverTimezone=GMT
    type: com.alibaba.druid.pool.DruidDataSource
    #   数据源其他配置
#    timeBetweenEvictionRunsMillis: 60000
#    minEvictableIdleTimeMillis: 300000
#    validationQuery: SELECT 1 FROM DUAL
#    testWhileIdle: true
#    testOnBorrow: false
#    testOnReturn: false
#    poolPreparedStatements: true
    #   配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
    driver-class-name: com.mysql.cj.jdbc.Driver
#    filters: stat,wall,log4j
#    maxPoolPreparedStatementPerConnectionSize: 20
#    useGlobalDataSourceStat: true
#    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=500
    tomcat:
      initial-size: 5
      max-active: 20
      max-wait: 60000
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 30000
      validation-query: SELECT 1 FROM DUAL
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
    hikari:
      minimum-idle: 5
    dbcp2:
      pool-prepared-statements: true

mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.wzz.entity
  configuration:
    # 配置日志
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
# 自定义文件上传路径
#file:
#  uploadDir: D:/Java/projects/exam_system-master/images/

file:
  uploadDir: C:/wwwroot/exam_system/server/images/
#  uploadDir: D:/Java/projects/exam_system-master/images/
